backend:
  name: github
  repo: rubenRP/cookbook

media_folder: static/assets
public_folder: assets

collections:
  - name: recipes
    label: Recipes
    folder: content/recipes
    path: "{{slug}}/index"
    media_folder: ""
    public_folder: ""
    create: true
    fields:
      - { name: title, label: Title }
      - { name: path, label: Path, required: false }
      - { name: date, label: Date, widget: date }
      - { name: published, label: Published, widget: "boolean", default: false }
      - {
          name: main_image,
          label: Main Image,
          widget: "image",
          required: false,
        }
      - name: taxonomy
        label: Taxonomy
        widget: "object"
        fields:
          - { name: category, label: Category, required: false }
          - { name: tag, label: Tags, widget: "list", required: false }
      - {
          name: ingredients,
          label: Ingredients,
          widget: "list",
          required: false,
        }
      - { name: servings, label: Servings, required: false }
      - { name: cooking_time, label: Cooking Time, required: false }
      - { name: source, label: Source, required: false }
      - { name: video, label: Video, required: false }
      - { name: body, label: Body, widget: markdown }
